### ISSUE TITLE
Could you release a new version of AnyEvent::Consul::Exec

### ISSUE THREAD

**Issue by wolfsage** [robn/AnyEvent-Consul-Exec#1]
I noticed AnyEvent::Consul::Exec from git has fixes for Consul >= 0.8.0 which disabled rexec by default, but the version on CPAN doesn't have those changes. Can you release a new version?

One risk I see is "Will the work successfully on an older Consul or with an older Test::Consul" ?

For the latter we could update Makefile.PL to require a newer Test::Consul, and for the former if it *does* break on < 0.8.0 we could version gate using enable_remote_exec in the .t files based on the consul version...

**Comment by robn** [comment]
I've released both AE::C::Exec and Test::Consul. They tested ok here; hopefully they are ok when placed near flame.

Thanks for pushing on these!
